/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ademaro
 */
public class InserirNumero_e_Genero extends javax.swing.JFrame {

    private String numero, genero;
    /**
     * Creates new form InserirNumero_e_Genero
     */
    public InserirNumero_e_Genero(String classeGramatical) {
       
        setResizable(false);
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(255,255,255));
        setVisible(true);
//        setSize(349, 200);
        URL caminhoImagem = this.getClass().getClassLoader().getResource("imagens/grammar (2).png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);
        
        generoBG.add(masculinoJRB);
        generoBG.add(femeninoJRB);
        
        numeroBG.add(singularJRB);
        numeroBG.add(pluralJRB);
        
        descricaoJLB.setText("Classificação do "+classeGramatical);
        
        numero = new String();
        genero = new String();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generoBG = new javax.swing.ButtonGroup();
        numeroBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        femeninoJRB = new javax.swing.JRadioButton();
        masculinoJRB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        pluralJRB = new javax.swing.JRadioButton();
        singularJRB = new javax.swing.JRadioButton();
        salvarJBT = new javax.swing.JButton();
        descricaoJLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gramática - Substantivo");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero"));
        jPanel1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        femeninoJRB.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        femeninoJRB.setText("Feminino");
        femeninoJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femeninoJRBActionPerformed(evt);
            }
        });

        masculinoJRB.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        masculinoJRB.setText("Masculino");
        masculinoJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoJRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(femeninoJRB)
                    .addComponent(masculinoJRB))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(masculinoJRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(femeninoJRB))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero"));
        jPanel2.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        pluralJRB.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        pluralJRB.setText("Plural");
        pluralJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pluralJRBActionPerformed(evt);
            }
        });

        singularJRB.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        singularJRB.setText("Singular");
        singularJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singularJRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pluralJRB)
                    .addComponent(singularJRB))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(singularJRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pluralJRB))
        );

        salvarJBT.setBackground(new java.awt.Color(255, 255, 255));
        salvarJBT.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        salvarJBT.setText("Salvar");
        salvarJBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarJBTActionPerformed(evt);
            }
        });

        descricaoJLB.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        descricaoJLB.setText("Classificação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(salvarJBT, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(descricaoJLB)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descricaoJLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salvarJBT, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarJBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJBTActionPerformed
        if(numero.equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(null, "Não selecionaste o numero");
        else if(genero.equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(null, "Não selecionaste o genero");
        else
            setVisible(false);
    }//GEN-LAST:event_salvarJBTActionPerformed

    private void singularJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singularJRBActionPerformed
        numero = "singular";
    }//GEN-LAST:event_singularJRBActionPerformed

    private void pluralJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pluralJRBActionPerformed
        numero = "plural";
    }//GEN-LAST:event_pluralJRBActionPerformed

    private void masculinoJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoJRBActionPerformed
       genero = "masculino";
    }//GEN-LAST:event_masculinoJRBActionPerformed

    private void femeninoJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femeninoJRBActionPerformed
       genero = "femenino";
    }//GEN-LAST:event_femeninoJRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirNumero_e_Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirNumero_e_Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirNumero_e_Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirNumero_e_Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirNumero_e_Genero("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descricaoJLB;
    private javax.swing.JRadioButton femeninoJRB;
    private javax.swing.ButtonGroup generoBG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton masculinoJRB;
    private javax.swing.ButtonGroup numeroBG;
    private javax.swing.JRadioButton pluralJRB;
    private javax.swing.JButton salvarJBT;
    private javax.swing.JRadioButton singularJRB;
    // End of variables declaration//GEN-END:variables

    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getGenero() {
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }
}
